appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: apcSIjMmrJgfRuWAc1dSUMefzYl8RKA+dEufo3hGz81k1kaTDJQIA+EisfJxm6tEwF4RSqQjYcceIAc8u4aSZuX8Nfxxh8j5KCUaw3NPYHEGIACz5sKq0GzeBou7kNV4yXIDJHeDAsDAVorCp+ww7RJNvQn/iITF/KM/S0gUKfgpxoqCiuSJ4O56yqEPaCSpZI+K5zthElGW0QqklBOyLApHfjwJ1655QB7aPIkcNxdOlv+gG8o/1mRb3a6wN0ShrSsxKxNywyZfUrDcp0pV6u7ScecWi2mqgs1lM6aOt8XwlybYZaKfjnAQmyh2kLcMe/C7qN9dpzZhra7j+ghBdE/bEQyO0fIdahhpn3wDFociNzO/ufUqlXedH5Mgzi8iLYol7cd7RPaaGfvg6K5BsdjfgbVTZmA+HV+a/qBU8/d0FdZacHp/h8Drp1+Mz68W5b8zPFA9uHWc9fPWj5KNuOKnwxwY3gF3NSywlp9SYVJTO8CIaqyc25I2285HsE/iJ24MZj/ohU3tpdBQ/3MF1Y0lSYNKO2HDqE1DPNGegFj3RKAtdiGs72O6peRxONO1uc970X9ZpeIJGnAbRt8QFjzQ1Kq5p4pwI42QWDISnYrNkeLiQ6mFDfDqXWs16lR6vZv9gsCNRaSND6dlTPKLt4u86eFBzKf9dauoDw2SjV4=}
bot:
  automerge: true
